-- 테이브 생성
create table KOPO_PRODUCT_VOLUME_TH2(
    REGIONID        VARCHAR2(20),
    PRODUCTGROUP    VARCHAR2(20),
    YEARWEEK        VARCHAR2(20),
    QTY NUMBER)

CREATE TABLE REGION_MASTER_TH2
(
    REGIONID    VARCHAR2(100),
    REGIONNAME  VARCHAR2(100)
)    

EDIT REGION_MASTER_TH2

INSERT INTO REGION_MASTER_TH2
    VALUES('A02','한국')

SELECT * FROM REGION_MASTER_TH2

--테이블구조 변경    
ALTER TABLE KOPO_PRODUCT_VOLUME_TH2
        ADD CONSTRAINTS KOPO_PRODUCT_VOLUME_TH2_PK
        PRIMARY KEY (REGIOMID, PRODUCTGROUP, YEARWEEK)

--데이터 삭제        
TRUNCATE TABLE KOPO_PRODUCT_VOLUME_TH2

SELECT * FROM KOPO_PRODUCT_VOLUME_TH2


    
-- 데이터 삽입
INSERT INTO KOPO_PRODUCT_VOLUME_TH2
    VALUES('A01','ST0001','201701',50)
    
    SELECT * FROM KOPO_PRODUCT_VOLUME_TH2




drop table REGION_MASTER_TH2