--조건절 (WHERE)사용
SELECT *FROM KOPO_PRODUCT_VOLUME

SELECT
    REGIONID, PRODUCTGROUP, YEARWEEK, VOLUME
FROM KOPO_PRODUCT_VOLUME
WHERE 1=1
AND PRODUCTGROUP = 'ST0002'
AND YEARWEEK >= '201515'
AND YEARWEEK <= '201516';

-- ST0002 상품의 201515,201516년도 제품만 조회
SELECT *FROM KOPO_PRODUCT_VOLUME
WHERE 1=1
AND PRODUCTGROUP = 'ST0002' 
AND (YEARWEEK = '201515' OR YEARWEEK = '201516')
--AND YEARWEEK >= 201515
--AND YEARWEEK <= 201516


-- 산술연산자 사용하기
SELECT
    VOLUME,
    VOLUME*1.1 AS WEIGHTED_VOL
FROM KOPO_PRODUCT_VOLUME
WHERE 1=1
AND PRODUCTGROUP = 'ST0001'

-- 산술연산자 예제
SELECT
   REGIONID, PRODUCTGROUP, YEARWEEK, VOLUME,
   ROUND(VOLUME * 1.1, 0) AS WEIGHTED_VOLUME -- round 소수점 자리를 정할수 있다
FROM KOPO_PRODUCT_VOLUME
WHERE 1=1
AND PRODUCTGROUP = 'ST0001'
AND YEARWEEK >= '201501'

--------
SELECT * FROM KOPO_PROMOTION


SELECT
    REGIONID,ITEM,TARGETWEEK,PLANWEEK,MAP_PRICE,IR,PMAP,PRODUCT,
    ROUND(PMAP * 0.9, 0) AS PMAP10
FROM KOPO_PROMOTION

------------
SELECT
    REGIONID,ITEM,TARGETWEEK,PLANWEEK,MAP_PRICE,IR,PMAP,PRODUCT,NVL(PMAP/NULLIF(MAP_PRICE, 0),0) AS PERCENT
FROM KOPO_PROMOTION

SELECT A.*,
    CASE WHEN MAP_PRICE = 0
            THEN 0
        WHEN MAP_PRICE IS NULL
            THEN 0
        ELSE A.PMAP/A.MAP_PRICE END AS PRO_PERCENT
    FROM KOPO_PROMOTION A
       