A01 지역의 

SELECT * FROM KOPO_CHANNEL_RESULT
WHERE 1=1
AND AP1NAME = 'BEST BUY'



SELECT * FROM KOPO_CHANNEL_RESULT
WHERE 1=1
    AND (YEARWEEK BETWEEN 201724 AND 201725 OR YEARWEEK BETWEEN 201727 AND 201729)
    AND AP1NAME  IN ('BEST BUY', 'HOME DEPOT')
    AND PRODUCT = 'HHP'
    AND AP2ID = 'A01'



SELECT * FROM KOPO_CHANNEL_RESULT
WHERE 1=1
AND AP2ID = 'A01'
AND 


-- 사용자 조건 입력받기
SELECT
   REGIONID, PRODUCTGROUP, YEARWEEK
FROM KOPO_PRODUCT_VOLUME
WHERE PRODUCTGROUP = &PRODUCT
OR YEARWEEK = '201544'


SELECT *FROM KOPO_PROMOTION

SELECT
    REGIONID, ITEM, TARGETWEEK, PLANWEEK, MAP_PRICE, IR, PMAP, PRODUCT
FROM KOPO_PROMOTION
WHERE 1=1
AND TARGETWEEK BETWEEN &


-- 정렬하기
SELECT
   REGIONID, PRODUCTGROUP, YEARWEEK
FROM KOPO_PRODUCT_VOLUME
WHERE PRODUCTGROUP = 'ST0001'
AND YEARWEEK BETWEEN 201501 AND 201503
ORDER BY YEARWEEK DESC, REGIONID ASC
-- DESC 내림차순, ASC 오름차순

SELECT *FROM KOPO_PRODUCT_VOLUME

SELECT
    REGIONID, PRODUCTGROUP, YEARWEEK
FROM KOPO_PRODUCT_VOLUME
WHERE 1=1
ORDER BY REGIONID ASC, PRODUCTGROUP ASC, YEARWEEK ASC




-- 대/소문자 변경하기
SELECT 
   UPPER(PRODUCT) AS CASE1,
   LOWER(PRODUCT) AS CASE2
FROM KOPO_CHANNEL_SEASONALITY_NEW


-- DUAL를 이용해서 테이블을 만들어서 연습할수있다
SELECT UPPER('abc') AS TEST 
FROM DUAL

-- 컬럼 합치기 COMCAT은 두 컬럼만 합칠수있다. 그러므로 ||를 사용해서 합치면 된다.
SELECT 
    CONCAT(REGIONID,CONCAT('_',PRODUCT)) AS KEYCOL1,
    REGIONID||'_'||PRODUCT AS KEYCOL2
FROM KOPO_CHANNEL_SEASONALITY_NEW


-- 컬럼 값 채우기
SELECT 
LPAD(PRODUCT, 10, '0')
FROM KOPO_CHANNEL_SEASONALITY_NEW


SELECT * FROM KOPO_CUSTOMERDATA

SELECT
LPAD(CUSTOMERCODE, 12, '*')
FROM KOPO_CUSTOMERDATA


-- 컬럼 값 제거하기
SELECT 
PRODUCT,
    TRIM(PRODUCT),      --공백제거
    LTRIM(PRODUCT,'PRO'),
    RTRIM(PRODUCT, '56')
FROM KOPO_CHANNEL_SEASONALITY_NEW


SELECT * FROM KOPO_CUSTOMERDATA

SELECT
CUSTOMERCODE,
LPAD(CUSTOMERCODE, 10, '0'),
SUBSTR(LPAD(CUSTOMERCODE, 10, '0'),1,6),
RPAD(SUBSTR(LPAD(CUSTOMERCODE, 10, '0'),1,6), 10, '*')
FROM KOPO_CUSTOMERDATA


SELECT
CUSTOMERCODE,
LPAD(CUSTOMERCODE, 10, '0'),
SUBSTR(LPAD(CUSTOMERCODE, 10, '0'),1,6),
REPLACE(SUBSTR(LPAD(CUSTOMERCODE, 10, '0'),1,6), ' ', '****')
FROM KOPO_CUSTOMERDATA
    

