select *from SORT_EXAMPLE


SELECT  WEEK, QTY FROM SORT_EXAMPLE WHERE 1=1 ORDER BY WEEK DESC

select *from SORT_EXAMPLE WHERE 1=1 ORDER BY WEEK DESC


--정렬할때 LPAD를 꼭 써줘야된다

--퀴즈 4번 문제
SELECT * FROM CASE_ORDER
WHERE 1=1
ORDER BY CASE PRODUCTGROUP
        WHEN 'REF' THEN 1
        WHEN 'OVEN' THEN 2
        WHEN 'WM' THEN 3
        ELSE 4
      END, YEAR ASC;
      
      
--예제
SELECT
CUSTOMERCODE,
LPAD(CUSTOMERCODE, 10, '0')AS STEP1,
SUBSTR(LPAD(CUSTOMERCODE, 10, '0'),1,6) AS STEP2,
RPAD(SUBSTR(LPAD(CUSTOMERCODE, 10, '0'),1,6), 10, '*') AS STEP3
FROM KOPO_CUSTOMERDATA

SELECT
CUSTOMERCODE,
LPAD(CUSTOMERCODE, 12, '0') AS STEP1,
SUBSTR(
    LPAD(CUSTOMERCODE, 12, '0'),
    -4) AS STEP2,
REPLACE(
    LPAD(CUSTOMERCODE, 12, '0'),
    SUBSTR(
    LPAD(CUSTOMERCODE, 12, '0'),
      -4), '****') AS STEP3
FROM KOPO_CUSTOMERDATA;


SELECT
CUSTOMERCODE,
LPAD(CUSTOMERCODE, &CODELEAN) AS STEP1,
SUBSTR(
    LPAD(CUSTOMERCODE, &CODELEAN),
    -4) AS STEP2,
REPLACE(
    LPAD(CUSTOMERCODE, &CODELEAN),
    SUBSTR(
    LPAD(CUSTOMERCODE, &CODELEAN),
      -4), '****') AS STEP3
FROM KOPO_CUSTOMERDATA;

-------수업 시작------
SELECT  ROUND(12.345,2) ,CEIL(12.345), FLOOR(12.345), MOD(12,10), POWER(3,2)  
from DUAL 



---예제1----
SELECT *FROM NUMBER_EXAMPLE

SELECT
    FIRST_NUMBER,SECOND_NUMBER,
    (FIRST_NUMBER / SECOND_NUMBER) AS AVG,
    ROUND((FIRST_NUMBER / SECOND_NUMBER),0) AS ROUND_EX,
    CEIL(FIRST_NUMBER / SECOND_NUMBER) AS CEIL_EX,
    FLOOR(FIRST_NUMBER / SECOND_NUMBER) AS FLOOR_EX,
    MOD(FIRST_NUMBER, SECOND_NUMBER) AS MOD_EX,
    POWER(FIRST_NUMBER,SECOND_NUMBER) AS POW_EX
FROM NUMBER_EXAMPLE


---예제2----
SELECT * FROM RMSE_MAE_EXAMPLE2

SELECT
    YEARWEEK, ACTUAL, FCST,
    ROUND((100*(1-ABS(FCST-ACTUAL)/ FCST)),2) AS ACCURACY,
ORDER BY YEARWEEK ASC
FROM RMSE_MAE_EXAMPLE2

-----------------------------날짜 함수-----------

SELECT
    SYSDATE,
    NEXT_DAY(SYSDATE,2),
     LAST_DAY(SYSDATE)
FROM DUAL

-------------년,월,일, 주차 정보를 보여줌------------

SELECT  TO_CHAR(SYSDATE-7, 'YYYYWW') ,
        TO_CHAR(SYSDATE, 'YYYYWW'), 
        TO_CHAR(SYSDATE-30, 'YYYYMMDD'), 
        TO_CHAR(SYSDATE, 'YYYYMMDD'), 
        TO_CHAR(SYSDATE-1, 'YYYYMMDD')
FROM DUAL


-----문자열 숫자로 바꾸는법----
SELECT * FROM SORT_EXAMPLE
ORDER BY TO_NUMBER(WEEK)


-------CASE 사용하기------------

SELECT * FROM KOPO_CHANNEL_SEASONALITY_NEW

SELECT 
    YEARWEEK,
    CASE WHEN QTY<1000 THEN 1000
         WHEN QTY>1000 AND QTY <10000 THEN 10000
         ELSE 30000 END AS QTY
FROM KOPO_CHANNEL_SEASONALITY_NEW


------DECODE 사용하기--------------
SELECT A.*
    ,DECODE(A.GENDER, 'MALE',1,'FEMALE',2,0) AS SORT_ORDER
    FROM KOPO_CUSTOMERDATA A
WHERE 1=1
ORDER BY SORT_ORDER