select * from PRO_FCST_RESULT_1WEEK

select * from PRO_FCST_RESULT_2WEEK

select * from PRO_FCST_RESULT_3WEEK

select * from PRO_FCST_RESULT_4WEEK

select * from PRO_FCST_RESULT_5WEEK

select * from PRO_FCST_RESULT_6WEEK

select * from PRO_FCST_RESULT_1WEEK
where 1=1
and 

select 
PRD_SEG1,PRD_SEG2,PRD_SEG3,
to_char(YEAR)as YEAR,
to_char(WEEK)as WEEK,
QTY,OUTFCST,

from PRO_FCST_RESULT_1WEEK

-----------------------------------------------------------------
SELECT * FROM KOPO_CHANNEL_SEASONALITY_NEW

SELECT REGIONID, PRODUCT, AVG(QTY) FROM
KOPO_CHANNEL_SEASONALITY_NEW
GROUP BY REGIONID, PRODUCT  --- GROUP BY 할때는 SELECT에도 같이 컬럼을 써줘야된다(집계대상)
ORDER BY REGIONID, PRODUCT
--HAVING(조건절)

----실습 예제----

SELECT REGIONID, PRODUCT, COUNT(QTY), SUM(QTY), AVG(QTY)
FROM
KOPO_CHANNEL_SEASONALITY_NEW
GROUP BY REGIONID, PRODUCT
HAVING SUM(QTY) > 100000
ORDER BY REGIONID, PRODUCT

--서브쿼리(from 절 안에 서브쿼리 작성)--

SELECT A.*
FROM (SELECT *
      FROM KOPO_CHANNEL_SEASONALITY_NEW
      WHERE 1=1
      AND REGIONID = 'A01') A

--서브쿼리(where 절 안에 서브쿼리 작성)--

SELECT *
FROM KOPO_CHANNEL_SEASONALITY_NEW
WHERE 1=1
AND REGIONID IN (SELECT REGIONID
                 FROM KOPO_PRODUCT_VOLUME);


-------------
SELECT * FROM
KOPO_CHANNEL_SEASONALITY_NEW

SELECT * FROM
KOPO_PROMOTION
WHERE 1=1
ABD REGIONID = 'A01'

CREATE TABLE KOPO_PROMOTION2(
REGIONID VARCHAR2(100),
PRODUCT VARCHAR2(100),
PRO_PROMOTION NUMBER)

SELECT * FROM KOPO_PROMOTION2

SELECT A.*
FROM KOPO_CHANNEL_SEASONALITY_NEW A
WHERE 1=1
AND REGIONID||PRODUCT IN(
    SELECT REGIONID||PRODUCT
    FROM
    KOPO_PROMOTION2);
    




-----서브쿼리(SELECT 절)-------
SELECT A.*,
        (SELECT AVG(QTY)
        FROM KOPO_CHANNEL_SEASONALITY_NEW
        WHERE REGIONID = A.REGIONID
        AND PRODUCT = A.PRODUCT
        GROUP BY A.REGIONID, A.PRODUCT) AS SUM_QTY
FROM KOPO_CHANNEL_SEASONALITY_NEW A

----------서브쿼리(whth)-------------------(메모리에 저장하기떄문에 성능이 더 좋음)
WITH TEST AS(
    SELECT REGIONID, PRODUCT, AVG(QTY)
    FROM KOPO_CHANNEL_SEASONALITY_NEW
    GROUP BY REGIONID, PRODUCT)
SELECT * FROM TEST


--MAE -> 각 실제값과 예측값의 절대값 차이의 평균
--RMSE -> 각 실제값과 예측값의 절대값 차이를 제곱한 후 평균울 산출 -> 이후 SQRT~!
WITH TEST AS(
    SELECT ITEM,
           YEARWEEK,
           QTY,
           ABS(QTY-PREDICTION) AS DIFF
    FROM RMSE_MAE_EXAMPLE
    )
SELECT AVG(DIFF)
FROM TEST A

----예제----
SELECT * FROM RMSE_MAE_EXAMPLE

WITH ASNWER AS(
    SELECT ITEM,
           YEARWEEK,
           QTY,
           POWER(ABS(QTY-PREDICTION),2) AS PO
    FROM RMSE_MAE_EXAMPLE
    )
SELECT ITEM, AVG(PO) AS MSE, SQRT(AVG(PO)) AS RMSE
FROM ASNWER
GROUP BY ITEM

---데이터 조인(x)--------
SELECT
    A.REFIONID
    B.REGIONNAME,
    A.APRODUCT,
    A.YEARWEEK,
    A.QTY
FROM KOPO_CHANNEL_SEASONALITY_NEW A,
     KOPO_REGION_MST B
     
SELECT * FROM KOPO_REGION_MST


--------데이터 조인(INNER)-----------

SELECT B.REGIONID, A.REGIONNAME, B.PRODUCT, B.YEARWEEK, B.QTY
FROM KOPO_REGION_MST A
INNER JOIN KOPO_CHANNEL_SEASONALITY_NEW B
ON A.REGIONID = B.REGIONID
--하지만 작은 데이터를 앞에 넣어야 속도가 더 빠르다.--

SELECT A.REGIONID, B.REGIONNAME, A.PRODUCT, A.YEARWEEK, A.QTY
FROM KOPO_REGION_MST B
INNER JOIN KOPO_CHANNEL_SEASONALITY_NEW A
ON B.REGIONID = A.REGIONID

SELECT A.*, B.*
FROM KOPO_REGION_MST B
INNER JOIN KOPO_CHANNEL_SEASONALITY_NEW A
ON B.REGIONID = A.REGIONID


-------데이터 조인(LEFT)-------------
SELECT A.*, B.*
FROM KOPO_REGION_MST B
LEFT JOIN KOPO_CHANNEL_SEASONALITY_NEW A
ON B.REGIONID = A.REGIONID

---------데이터가 붙지 않는 것을 보고싶을때----------

SELECT * FROM
(
    SELECT A.*, B.*
    FROM KOPO_REGION_MST B
    LEFT JOIN KOPO_CHANNEL_SEASONALITY_NEW A
    ON B.REGIONID = A.REGIONID
)
WHERE REGIONNAME IS NULL;

SELECT DISTINCT A.REGIONID
FROM
KOPO_CHANNEL_SEASONALITY_NEW A
LEFT JOIN KOPO_REGION_MST B
ON A.REGIONID = B.REGIONID
WHERE B.REGIONNAME IS NULL;

SELECT A.*, B.*
FROM
KOPO_CHANNEL_SEASONALITY_NEW A
RIGHT JOIN KOPO_REGION_MST B
ON A.REGIONID = B.REGIONID
WHERE A.QTY IS NULL;

------데이터 조인(FULL OUTER)--------(양쪽 데이터를 모두 살릴수 있다)
SELECT A.*, B.*
FROM
KOPO_CHANNEL_SEASONALITY_NEW A
RIGHT JOIN KOPO_REGION_MST B
ON A.REGIONID = B.REGIONID
WHERE 1=1
AND A.REGIONID IS NULL;



---------예제------------
SELECT A.*, B.*
FROM CUSTOMER_NAME A
INNER JOIN CUSTOMERDATA B
ON A.CUSTID = B.CUSTID;


SELECT * FROM CUSTOMERDATA

