-----pivot----------(화면에 뿌려주고 가속성을 높인다)
SELECT * FROM DT_RESULT_FINAL2

SELECT 
    *
     FROM (
        SELECT  *
        FROM DT_RESULT_FINAL2
)
PIVOT( 
    SUM(SALES)
    FOR MEASURE IN 
   ('REAL-QTY' AS REAL_QTY,'PREDICTION-QTY' AS PREDICTION_QTY)
)
ORDER BY PRODUCTGROUP, PRODUCT, ITEM, YEARWEEK

---예제---------
SELECT * FROM KOPO_CHANNEL_SEASONALITY_NEW

SELECT 
    *
     FROM (
        SELECT REGIONID, PRODUCT,
        SUBSTR(YEARWEEK, 5) AS WEEK,
        ROUND(AVG(QTY)) AS QTY
        FROM KOPO_CHANNEL_SEASONALITY_NEW
        GROUP BY REGIONID, PRODUCT, SUBSTR(YEARWEEK, 5)
)
PIVOT( 
    SUM(QTY)
    FOR WEEK IN 
   ('01' AS W01,'02' AS W02,'03' AS W03,'52' AS W52,'53' AS W53)
)
ORDER BY REGIONID, PRODUCT

SELECT 
    *
     FROM (
        SELECT REGIONID, PRODUCT,
        SUBSTR(YEARWEEK, 5) AS WEEK,
        ROUND(AVG(QTY)) AS QTY
        FROM KOPO_CHANNEL_SEASONALITY_NEW
        GROUP BY REGIONID, PRODUCT, SUBSTR(YEARWEEK, 5)
)
PIVOT( 
    SUM(QTY)
    FOR WEEK IN 
   ('01' ,'02','03','04','05')
)
ORDER BY REGIONID, PRODUCT

-------------------------------------------------------------------------------

----UNPIVOT---------(열을 행으로)

SELECT * FROM DT_RESULT_FINAL3

WITH T AS( 
    SELECT * FROM DT_RESULT_FINAL3
)
SELECT MEASURE, PRODUCTGROUP, PRODUCT, ITEM, YEARWEEK, QTY FROM T
UNPIVOT(QTY FOR MEASURE IN(REAL_QTY, PREDICTION_QTY))


WITH T AS( 
    SELECT 
    *
     FROM (
        SELECT REGIONID, PRODUCT,
        SUBSTR(YEARWEEK, 5) AS WEEK,
        ROUND(AVG(QTY),0) AS QTY
        FROM KOPO_CHANNEL_SEASONALITY_NEW
        GROUP BY REGIONID, PRODUCT, SUBSTR(YEARWEEK, 5)
)
PIVOT( 
    SUM(QTY)
    FOR WEEK IN 
   ('01' AS W01,'02' AS W02,'03' AS W03,'52' AS W52,'53' AS W53)
)
)
SELECT * FROM T
UNPIVOT(QTY FOR WEEK IN('01' AS W01,'02' AS W02,'03' AS W03,'52' AS W52,'53' AS W53))
ORDER BY REGIONID, PRODUCT, WEEK

-------------------------------------------------------------------------------

SELECT 
FROM
B.REGIONID, AVG(B.PRO_PROMOTION)
