CREATE TABLE KOPO_PRODUCT_VOLUME_LTH
(
    REGIONID        VARCHAR2(20),
    PRODUCTGROUP    VARCHAR2(20),
    YEARWEEK        VARCHAR2(20),
    QTY             NUMBER
)

SELECT * FROM KOPO_PRODUCT_VOLUME_LTH

CREATE TABLE REGION_MASTER_LTH
(
    REGIONID        VARCHAR2(100),
    REGIONNAME      VARCHAR2(100)
)

SELECT * FROM REGION_MASTER_LTH

