SELECT A.*, 
ROW_NUMBER() OVER(ORDER BY SUM_QTY DESC) AS REGION_PRODUCT_ROW, 
RANK() OVER(ORDER BY SUM_QTY DESC) AS REGION_PRODUCT_RANK,
DENSE_RANK() OVER(ORDER BY SUM_QTY DESC) AS REGION_PRODUCT_DRANK
FROM
(
SELECT REGIONID,
        PRODUCT,
        SUM(QTY) AS SUM_QTY
        FROM KOPO_CHANNEL_SEASONALITY_NEW
        GROUP BY REGIONID, PRODUCT
        ORDER BY REGIONID, SUM_QTY
)A

SELECT A.*,
    ROW_NUMBER() OVER(PARTITION BY REGIONID ORDER BY SUM_QTY DESC) AS REGION_PRODUCT_ROW, -- 지역별로 순위를 정한다....(PARTITION)
    RANK() OVER(PARTITION BY REGIONID ORDER BY SUM_QTY DESC) AS REGION_PRODUCT_RANK,
    DENSE_RANK() OVER(PARTITION BY REGIONID ORDER BY SUM_QTY DESC) AS REGION_PRODUCT_DRANK
    FROM
    (
        SELECT REGIONID,
        PRODUCT,
        SUM(QTY) AS SUM_QTY
        FROM KOPO_CHANNEL_SEASONALITY_NEW
        GROUP BY REGIONID, PRODUCT
        ORDER BY REGIONID, SUM_QTY
    )A


SELECT * FROM KOPO_CHANNEL_SEASONALITY_NEW

SELECT REGIONID, PRODUCT
FROM KOPO_CHANNEL_SEASONALITY_NEW
GROUP BY REGIONID,PRODUCT

