SELECT A.PRD_SEG1, A.PRD_SEG2, A.PRD_SEG3, A.YEAR, A.WEEK, A.QTY AS ACTUAL, F.OUTFCST AS W6, E.OUTFCST AS W5, D.OUTFCST AS W4, C.OUTFCST AS W3, B.OUTFCST AS W2, A.OUTFCST AS W1, 
        NVL(ABS(F.OUTFCST-A.QTY), A.QTY) AS ABS8W_W6, NVL(ABS(E.OUTFCST-A.QTY), A.QTY) AS ABS8W_W5, NVL(ABS(D.OUTFCST-A.QTY), A.QTY) AS ABS8W_W4, NVL(ABS(C.OUTFCST-A.QTY), A.QTY) AS ABS8W_W3, 
        NVL(ABS(B.OUTFCST-A.QTY), A.QTY) AS ABS8W_W2, NVL(ABS(A.OUTFCST-A.QTY), A.QTY) AS ABS8W_W1, 
        CASE WHEN NVL(F.OUTFCST,0) = 0 OR A.QTY = 0 THEN 0
             WHEN (A.QTY/F.OUTFCST) > 2 THEN 0
             ELSE 1-(NVL(ABS(F.OUTFCST-A.QTY), A.QTY)/F.OUTFCST) END AS ACC8W_W6,
        CASE WHEN NVL(E.OUTFCST,0) = 0 OR A.QTY = 0 THEN 0
             WHEN (A.QTY/E.OUTFCST) > 2 THEN 0
             ELSE 1-(NVL(ABS(E.OUTFCST-A.QTY), A.QTY)/E.OUTFCST) END AS ACC8W_W5,
        CASE WHEN NVL(D.OUTFCST,0) = 0 OR A.QTY = 0 THEN 0
             WHEN (A.QTY/D.OUTFCST) > 2 THEN 0
             ELSE 1-(NVL(ABS(D.OUTFCST-A.QTY), A.QTY)/D.OUTFCST) END AS ACC8W_W4,
        CASE WHEN NVL(C.OUTFCST,0) = 0 OR A.QTY = 0 THEN 0
             WHEN (A.QTY/C.OUTFCST) > 2 THEN 0
             ELSE 1-(NVL(ABS(C.OUTFCST-A.QTY), A.QTY)/C.OUTFCST) END AS ACC8W_W3,
        CASE WHEN NVL(B.OUTFCST,0) = 0 OR A.QTY = 0 THEN 0
             WHEN (A.QTY/B.OUTFCST) > 2 THEN 0
             ELSE 1-(NVL(ABS(B.OUTFCST-A.QTY), A.QTY)/B.OUTFCST) END AS ACC8W_W2,
        CASE WHEN NVL(A.OUTFCST,0) = 0 OR A.QTY = 0 THEN 0
             WHEN (A.QTY/A.OUTFCST) > 2 THEN 0
             ELSE 1-(NVL(ABS(A.OUTFCST-A.QTY), A.QTY)/A.OUTFCST) END AS ACC8W_W1,
        NVL(F.OUTFCST,0)*
        CASE WHEN NVL(F.OUTFCST,0) = 0 OR A.QTY = 0 THEN 0
             WHEN (A.QTY/F.OUTFCST) > 2 THEN 0
             ELSE 1-(NVL(ABS(F.OUTFCST-A.QTY), A.QTY)/F.OUTFCST) END AS ACC8W_QTY_W6,
        NVL(E.OUTFCST,0)*
        CASE WHEN NVL(E.OUTFCST,0) = 0 OR A.QTY = 0 THEN 0
             WHEN (A.QTY/E.OUTFCST) > 2 THEN 0
             ELSE 1-(NVL(ABS(E.OUTFCST-A.QTY), A.QTY)/E.OUTFCST) END AS ACC8W_QTY_W5,
        NVL(D.OUTFCST,0)*
        CASE WHEN NVL(D.OUTFCST,0) = 0 OR A.QTY = 0 THEN 0
             WHEN (A.QTY/D.OUTFCST) > 2 THEN 0
             ELSE 1-(NVL(ABS(D.OUTFCST-A.QTY), A.QTY)/D.OUTFCST) END AS ACC8W_QTY_W4,
        NVL(C.OUTFCST,0)*
        CASE WHEN NVL(C.OUTFCST,0) = 0 OR A.QTY = 0 THEN 0
             WHEN (A.QTY/C.OUTFCST) > 2 THEN 0
             ELSE 1-(NVL(ABS(C.OUTFCST-A.QTY), A.QTY)/C.OUTFCST) END AS ACC8W_QTY_W3,
        NVL(B.OUTFCST,0)*
        CASE WHEN NVL(B.OUTFCST,0) = 0 OR A.QTY = 0 THEN 0
             WHEN (A.QTY/B.OUTFCST) > 2 THEN 0
             ELSE 1-(NVL(ABS(B.OUTFCST-A.QTY), A.QTY)/B.OUTFCST) END AS ACC8W_QTY_W2,
        NVL(A.OUTFCST,0)*
        CASE WHEN NVL(A.OUTFCST,0) = 0 OR A.QTY = 0 THEN 0
             WHEN (A.QTY/A.OUTFCST) > 2 THEN 0
             ELSE 1-(NVL(ABS(A.OUTFCST-A.QTY), A.QTY)/A.OUTFCST) END AS ACC8W_QTY_W1,
        (NVL(F.OUTFCST,0)+NVL(E.OUTFCST,0)+NVL(D.OUTFCST,0)+NVL(C.OUTFCST,0)+NVL(B.OUTFCST,0)+NVL(A.OUTFCST,0)) / (NVL2(F.OUTFCST,1,0)+ NVL2(E.OUTFCST,1,0)+ NVL2(D.OUTFCST,1,0)+ NVL2(C.OUTFCST,1,0)+ NVL2(B.OUTFCST,1,0)+ NVL2(A.OUTFCST,1,0)) AS FCST_AVG,
        (NVL(F.OUTFCST,0)*
        CASE WHEN NVL(F.OUTFCST,0) = 0 OR A.QTY = 0 THEN 0
             WHEN (A.QTY/F.OUTFCST) > 2 THEN 0
             ELSE 1-(NVL(ABS(F.OUTFCST-A.QTY), A.QTY)/F.OUTFCST) END +
        NVL(E.OUTFCST,0)*
        CASE WHEN NVL(E.OUTFCST,0) = 0 OR A.QTY = 0 THEN 0
             WHEN (A.QTY/E.OUTFCST) > 2 THEN 0
             ELSE 1-(NVL(ABS(E.OUTFCST-A.QTY), A.QTY)/E.OUTFCST) END +
        NVL(D.OUTFCST,0)*
        CASE WHEN NVL(D.OUTFCST,0) = 0 OR A.QTY = 0 THEN 0
             WHEN (A.QTY/D.OUTFCST) > 2 THEN 0
             ELSE 1-(NVL(ABS(D.OUTFCST-A.QTY), A.QTY)/D.OUTFCST) END +
        NVL(C.OUTFCST,0)*
        CASE WHEN NVL(C.OUTFCST,0) = 0 OR A.QTY = 0 THEN 0
             WHEN (A.QTY/C.OUTFCST) > 2 THEN 0
             ELSE 1-(NVL(ABS(C.OUTFCST-A.QTY), A.QTY)/C.OUTFCST) END +
        NVL(B.OUTFCST,0)*
        CASE WHEN NVL(B.OUTFCST,0) = 0 OR A.QTY = 0 THEN 0
             WHEN (A.QTY/B.OUTFCST) > 2 THEN 0
             ELSE 1-(NVL(ABS(B.OUTFCST-A.QTY), A.QTY)/B.OUTFCST) END +
        NVL(A.OUTFCST,0)*
        CASE WHEN NVL(A.OUTFCST,0) = 0 OR A.QTY = 0 THEN 0
             WHEN (A.QTY/A.OUTFCST) > 2 THEN 0
             ELSE 1-(NVL(ABS(A.OUTFCST-A.QTY), A.QTY)/A.OUTFCST) END ) / 6 AS ACC_AVG
FROM PRO_FCST_RESULT_1WEEK_TT A
LEFT JOIN PRO_FCST_RESULT_2WEEK_TT B
ON A.PRD_SEG3 = B.PRD_SEG3
LEFT JOIN PRO_FCST_RESULT_3WEEK_TT C
ON A.PRD_SEG3 = C.PRD_SEG3
LEFT JOIN PRO_FCST_RESULT_4WEEK_TT D
ON A.PRD_SEG3 = D.PRD_SEG3
LEFT JOIN PRO_FCST_RESULT_5WEEK_TT E
ON A.PRD_SEG3 = E.PRD_SEG3
LEFT JOIN PRO_FCST_RESULT_6WEEK_TT F
ON A.PRD_SEG3 = F.PRD_SEG3;


SELECT A.PRD_SEG1, A.PRD_SEG2, A.PRD_SEG3, A.YEAR, A.WEEK, A.QTY AS ACTUAL,
        F.OUTFCST AS W6, E.OUTFCST AS W5, D.OUTFCST AS W4, C.OUTFCST AS W3, B.OUTFCST AS W2, A.OUTFCST AS W1,
        NVL(ABS(F.OUTFCST-A.QTY), A.QTY) AS ABS8W_W6, NVL(ABS(E.OUTFCST-A.QTY), A.QTY) AS ABS8W_W5, NVL(ABS(D.OUTFCST-A.QTY), A.QTY) AS ABS8W_W4, NVL(ABS(C.OUTFCST-A.QTY), A.QTY) AS ABS8W_W3, 
        NVL(ABS(B.OUTFCST-A.QTY), A.QTY) AS ABS8W_W2, NVL(ABS(A.OUTFCST-A.QTY), A.QTY) AS ABS8W_W1
FROM PRO_FCST_RESULT_1WEEK_TT A
LEFT JOIN PRO_FCST_RESULT_2WEEK_TT B
ON A.PRD_SEG3 = B.PRD_SEG3
LEFT JOIN PRO_FCST_RESULT_3WEEK_TT C
ON A.PRD_SEG3 = C.PRD_SEG3
LEFT JOIN PRO_FCST_RESULT_4WEEK_TT D
ON A.PRD_SEG3 = D.PRD_SEG3
LEFT JOIN PRO_FCST_RESULT_5WEEK_TT E
ON A.PRD_SEG3 = E.PRD_SEG3
LEFT JOIN PRO_FCST_RESULT_6WEEK_TT F
ON A.PRD_SEG3 = F.PRD_SEG3;

select * from tabs

select * from KOPO_ST_김효관_FINAL4

select * from COMMON_GROUP4_NEW

select * from 상품정보

select * from 주문정보