CREATE TABLE KOPO_CATEGORY
(
    CATCODE     VARCHAR2(100),
    NAME        VARCHAR2(100),
    constraint PK_KOPO_CATEGORY primary key (CATCODE));
    
SELECT * FROM KOPO_CATEGORY;

DROP TABLE KOPO_CATEGORY

INSERT INTO
    KOPO_CATEGORY
    VALUES('A05','e')

CREATE TABLE KOPO_USERS
(
    USERID      VARCHAR2(100),
    USERNAME    VARCHAR2(100),
    PASSWORD    VARCHAR2(100),
    CARD_COMPANY    VARCHAR2(100),
    CARD_NO     VARCHAR2(100),
    ADDRESS     VARCHAR2(100),
    TEL         VARCHAR2(100),
    EMAIL       VARCHAR2(100),
    constraint PK_KOPO_USERS primary key (USERID))
    
SELECT * FROM KOPO_USERS

DROP TABLE KOPO_USERS

INSERT INTO
    KOPO_USERS
    VALUES('B05','05','05','05','05','05','05','05')

CREATE TABLE KOPO_PRODUCT
(
    PRODUCTCODE     VARCHAR2(100),
    CARCODE_FK      VARCHAR2(100),
    NAME            VARCHAR2(100),
    COMPANY         VARCHAR2(100),
    PRICE           NUMBER,
    BUY_NUM         NUMBER,
    STATUS          VARCHAR2(100),
    DETAILS         VARCHAR2(100),
    C_DATE          VARCHAR2(100),
    CONSTRAINT PK_KOPO_PRODUCT PRIMARY KEY(PRODUCTCODE),CONSTRAINT FK_KOPO_PRODUCT FOREIGN KEY(CARCODE_FK) REFERENCES KOPO_CATEGORY(CATCODE)
    ON DELETE CASCADE
    )
    
SELECT * FROM KOPO_PRODUCT

DROP TABLE KOPO_PRODUCT

INSERT INTO
    KOPO_PRODUCT
    VALUES('AA05','A05','05','05','05','05','05','05','05')


CREATE TABLE KOPO_ORDER
(
    ORDERID     VARCHAR2(100),
    USERID_FK      VARCHAR2(100),
    ORDER_STATUS    VARCHAR2(100),
    ORDER_DATE      VARCHAR2(100),
    ORDER_PRICE     NUMBER,
    CONSTRAINT PK_KOPO_ORDER PRIMARY KEY(ORDERID),
    CONSTRAINT FK_KOPO_ORDER FOREIGN KEY(USERID_FK) REFERENCES KOPO_USERS(USERID))
    
SELECT * FROM KOPO_ORDER

INSERT INTO
    KOPO_ORDER
    VALUES('C05','B05','05','05','05')

DELETE FROM KOPO_ORDER

CREATE TABLE KOPO_ORDER_LIST
(
    ORDERID_FK      VARCHAR2(100),
    PRODUCTCODE_FK  VARCHAR2(100),
    COUNT           NUMBER,
    CONSTRAINT PK_KOPO_ORDER_LIST PRIMARY KEY(ORDERID_FK, PRODUCTCODE_FK),
    CONSTRAINT FK_KOPO_ORDER_LIST FOREIGN KEY(ORDERID_FK) REFERENCES KOPO_ORDER(ORDERID),
    CONSTRAINT FK_KOPO_ORDER_LIST2 FOREIGN KEY(PRODUCTCODE_FK) REFERENCES KOPO_PRODUCT(PRODUCTCODE))
    
SELECT * FROM KOPO_ORDER_LIST


INSERT INTO
    KOPO_ORDER_LIST
    VALUES('C05','AA05','05')   