select * from tabs

select * from KOPO_REGION_MST_임태현

select * from QUERY_TH

drop table QUERY_TH

select * from QUERY_TH

select REGIONID, PRODUCTGROUP, PRODUCT, ITEM, YEARWEEK, YEAR, WEEK, QTY, HOLIDAY, HCLUS, PROMOTION, PRO_PERCENT,
        case when HOLIDAY = 'Y' then 1
            else 0
        end as HOLIDAY_NUM,
        case when PROMOTION = 'Y' then 1
            else 0
        end as PROMOTION_NUM
from QUERY_TH

-- 컬럼 값 대/소문자로 바꾸기
select
    LOWER(REGIONID) AS CASE1,
    UPPER(REGIONID) AS CASE2
FROM QUERY_TH

-- 컬럼값 합치기
--1
SELECT
    CONCAT(PRODUCTGROUP,CONCAT('_',PRODUCT)) AS CON
FROM QUERY_TH
--2
SELECT
    PRODUCTGROUP||'_'||PRODUCT AS CON
FROM QUERY_TH

-- 컬럼값 추출하기
SELECT
    REGIONID,
    SUBSTR(REGIONID,1,5) AS "5"
FROM QUERY_TH

--컬럼값 채우기
SELECT
    LPAD(PRODUCTGROUP,3,'A')
FROM QUERY_TH

SELECT
    RPAD(PRODUCTGROUP,2,'a')
FROM QUERY_TH

--컬럼값 제거하기
SELECT
    LTRIM(PRODUCTGROUP,'PG')
FROM QUERY_TH

SELECT
    RTRIM(PRODUCTGROUP, '02')
FROM QUERY_TH

SELECT LENGTH(TRIM(' ABC '))
FROM DUAL

--컬럼값 변경하기
SELECT
    REGIONID,
    REPLACE(REGIONID, 'SEOUL', 'JEONJU')
FROM QUERY_TH

--연습
SELECT
    QTY,
    RPAD(SUBSTR(LPAD(QTY,4,0),1,2),4,'*')
FROM QUERY_TH
    
SELECT REPLACE('YOU ARE MY ANGEL',' ', '=') AS "결과" FROM DUAL;

--숫자함수
SELECT
    ROUND(12.345,2),
    CEIL(12.345),
    FLOOR(12.345),
    MOD(12,10),
    power(3,2)
FROM DUAL

--날짜함수
SELECT
    SYSDATE,
    NEXT_DAY(SYSDATE,2),
    LAST_DAY(SYSDATE)
FROM DUAL

--DECODE함수
SELECT A.*,
    DECODE(A.HOLIDAY, 'Y',1,'N',0) AS HOL_NUM
FROM QUERY_TH A

--집계함수
SELECT REGIONID, PRODUCT, AVG(QTY)
FROM QUERY_TH
GROUP BY REGIONID, PRODUCT
ORDER BY REGIONID, PRODUCT

--GROUP BY 조건
SELECT REGIONID, PRODUCT, AVG(QTY)
FROM QUERY_TH
GROUP BY REGIONID, PRODUCT
HAVING AVG(QTY)>1000
ORDER BY REGIONID, PRODUCT

--조인 INNER
SELECT 

    