SELECT * FROM KOPO_REGION_MST

SELECT * FROM KOPO_CHANNEL_SEASONALITY_NEW

--INNER JOIN
SELECT B.REGIONID, A.REGIONNAME, B.PRODUCT, B.YEARWEEK, B.QTY
FROM KOPO_REGION_MST A
INNER JOIN KOPO_CHANNEL_SEASONALITY_NEW B
on A.REGIONID = B.REGIONID

SELECT A.REGIONID, B.REGIONNAME, A.PRODUCT, A.YEARWEEK, A.QTY
FROM KOPO_CHANNEL_SEASONALITY_NEW A
INNER JOIN KOPO_REGION_MST B
on A.REGIONID = B.REGIONID

--LEFT JOIN
SELECT A.REGIONID, B.REGIONNAME, A.PRODUCT, A.YEARWEEK, A.QTY 
FROM KOPO_CHANNEL_SEASONALITY_NEW A
LEFT JOIN KOPO_REGION_MST B
ON A.REGIONID = B.REGIONID

SELECT * FROM
(
    SELECT A.REGIONID, B.REGIONNAME, A.PRODUCT, A.YEARWEEK, A.QTY 
    FROM KOPO_CHANNEL_SEASONALITY_NEW A
    LEFT JOIN KOPO_REGION_MST B
    ON A.REGIONID = B.REGIONID
    )
    WHERE REGIONID = 'A77'
    
--RIGHT JOIN
SELECT A.REGIONID, B.REGIONNAME, A.PRODUCT, A.YEARWEEK, A.QTY
FROM KOPO_CHANNEL_SEASONALITY_NEW A
RIGHT JOIN KOPO_REGION_MST B
on A.REGIONID = B.REGIONID

SELECT * FROM
(
    SELECT A.REGIONID, B.REGIONNAME, A.PRODUCT, A.YEARWEEK, A.QTY
    FROM KOPO_CHANNEL_SEASONALITY_NEW A
    RIGHT JOIN KOPO_REGION_MST B
    on A.REGIONID = B.REGIONID
    )
    WHERE REGIONID IS NULL
    
--PIVOT
SELECT * FROM DT_RESULT_FINAL2

SELECT * FROM DT_RESULT_FINAL2
ORDER BY PRODUCTGROUP, PRODUCT, ITEM, YEARWEEK, MEASURE

SELECT 
    *
     FROM (
        SELECT  *
        FROM DT_RESULT_FINAL2
)
PIVOT( 
    SUM(SALES)
    FOR MEASURE IN 
   ('REAL-QTY' AS REAL_QTY,'PREDICTION-QTY' AS PREDICTION_QTY)
)
ORDER BY PRODUCTGROUP, PRODUCT, ITEM, YEARWEEK

--연습문제
SELECT * FROM KOPO_CHANNEL_SEASONALITY_NEW

SELECT * FROM
(
    SELECT REGIONID,PRODUCT, substr(YEARWEEK,5) AS WEEK, ROUND(AVG(QTY)) AS QTY
    FROM KOPO_CHANNEL_SEASONALITY_NEW
    GROUP BY REGIONID, PRODUCT, substr(YEARWEEK,5)
)
PIVOT(
        SUM(QTY)
        FOR WEEK IN
        ('01' AS W01, '02' AS W02, '03' AS W03, '52' AS W52, '53' AS W53)
     )
ORDER BY REGIONID, PRODUCT

--UNPIVOT
SELECT * FROM DT_RESULT_FINAL3

WITH T AS(
    SELECT * FROM DT_RESULT_FINAL3
)
SELECT MEASURE, PRODUCTGROUP, PRODUCT, ITEM, YEARWEEK, QTY
FROM T
UNPIVOT(QTY FOR MEASURE IN(REAL_QTY, PREDICTION_QTY))

--연습문제
WITH T AS
(
    SELECT * FROM
    (
        SELECT REGIONID,PRODUCT, substr(YEARWEEK,5) AS WEEK, ROUND(AVG(QTY)) AS QTY
        FROM KOPO_CHANNEL_SEASONALITY_NEW
        GROUP BY REGIONID, PRODUCT, substr(YEARWEEK,5)
    )
    PIVOT(
            SUM(QTY)
            FOR WEEK IN
            ('01' AS W01, '02' AS W02, '03' AS W03, '52' AS W52, '53' AS W53)
         )
    ORDER BY REGIONID, PRODUCT
)
SELECT REGIONID,PRODUCT,WEEK,QTY
FROM T
UNPIVOT(QTY FOR WEEK IN (W01,W02,W03,W52,W53))

--일반 테이블 생성하기
CREATE TABLE CUSTOMERDATA
(
    CUSTID VARCHAR(200),
    AVERAGEPRICE NUMBER,
    EMI NUMBER,
    DEVICECOUNT NUMBER,
    PRODUCTAGE NUMBER,
    CUSTTYPE NUMBER
    )