create table KOPO_REGION_MASTER_TH3
(
REGIONID    VARCHAR2(100),
REGIONNAME  VARCHAR2(100))

EDIT KOPO_REGION_MASTER_TH3



SELECT * FROM KOPO_PRODUCT_VOLUME

EDIT KOPO_PRODUCT_VOLUME

TRUNCATE TABLE KOPO_PRODUCT_VOLUME

SELECT * FROM
KOPO_REGION_MASTER_TH3 A
INNER JOIN KOPO_PRODUCT_VOLUME B
ON A.REGIONID = B.REGIONID

EDIT KOPO_PRODUCT_VOLUME

DROP TABEL KOPO_REGION_MASTER_TH3



SELECT * FROM
KOPO_REGION_MASTER_TH3 A
LEFT JOIN KOPO_PRODUCT_VOLUME B
ON A.REGIONID = B.REGIONID